### ISSUE TITLE
Taken-over server could be passively monitored to leak secrets

### ISSUE THREAD

**Issue by divVerent** [syseleven/shared-secrets#1]
If the server has been taken over by an attacker, the attacker may add code to leak the secrets.

This is caused by the server performing the encryption/decryption of the secrets.

Suggested "minimal" solution:

- Client-side encryption/decryption of the secrets.
- Server only gets to encrypt/decrypt a per-message key, not the message itself.

After that, a compromised server can only leak the access times and IPs of the secrets and their per-message key, not the secrets themselves. An attacker therefore needs to not just take over the server, but also monitor the chat systems used to transmit the URLs - or alternatively, change the client-side code of the system (which may be discovered, thus it's a higher bar).

**Comment by weizenspreu** [comment]
The problem with client-side encryption/decryption is, that there has to be some setup in place on the client-side. However, the typical absence of such a setup is the reason for actually creating the server-based solution.

Encryption/Decryption may be done through client-side JavaScript code to replace a local setup, but that JavaScript code may just get compromised as well.

**Comment by divVerent** [comment]
That's true. I'd still prefer the JS way, as at least the user then has a CHANCE to verify they're actually running the code they thing they do. Plus, at a later time there then could be external tools/extensions that are compatible to the server but provide a more verifiable way to make sure you're actually running the code you think they do.

But indeed, this issue is also the main issue with MEGA - still probably worth documenting to set people's security expectations.

**Comment by weizenspreu** [comment]
A requested feature has been to have an additional symmetric encryption to have something so share through a second channel. Implementing the symmetric encryption through client-side JavaScript could probably prevent the server from reading the actual secret.

This would require that the secret is first encrypted symmetrically and then asymmetrically.

**Comment by divVerent** [comment]
Right, and this feature request would basically also implement what's suggested here (namely, having the server only actually encrypt/decrypt a per-message key, not the message itself - or, security-equivalently, two layers of encryption and having the server handle the outer layer).

**Comment by weizenspreu** [comment]
The test installation on https://secrets.syseleven.de/ now provides an optional password-protection feature that's based on the [asmCrypto](https://github.com/vibornoff/asmcrypto.js/) library. Before publishing the new version, I'm going to test it in a chrooted environment.

**Comment by divVerent** [comment]
Cool! One can also now quite easily make sure this feature can't leak the secret on the receiver's side at least - just disconnect the network before client-side decrypting and clear browsing data afterwards (this is paranoid, yes, but also shows that the password feature is about as secure as it gets against network-side attackers).

**Comment by divVerent** [comment]
PBKDF2_HMAC_SHA256 - good choice, but the workFactor could probably a bit bigger (try tuning it so encrypting takes about 1 or 2 seconds on a slow device).

**Comment by weizenspreu** [comment]
The new version 0.3b0 has been published which includes the client-side password-protection feature. The encryption key is generated via PBKDF2-HMAC-SHA256 with 1024 rounds (which can be customized through the "workFactor" variable in the JavaScript code, if necessary). AES-GCM is used for the encryption. The nonce used for the AES-GCM encryption/decryption is always [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] - the uniqueness of the nonce in relation to the key is given by providing a 256-bit pseudorandom salt to the PBKDF2 call.

As the local decryption of the secret only happens after the secret has been retrieved from the server, a user that fails to decrypt the secret will not be able to retrieve the (locally encrypted) secret again.

**Comment by weizenspreu** [comment]
The local encryption now doesn't rely on a server-provided salt anymore but uses [RandomSource.getRandomValues()](https://developer.mozilla.org/de/docs/Web/API/RandomSource/getRandomValues) to generate it locally in the browser:

> The RandomSource.getRandomValues() method lets you get cryptographically random values. The array given as the parameter is filled with random numbers (random in its cryptographic meaning).

In addition, [subresource integrity](http://www.w3.org/TR/SRI/) has been introduced for all javascript files and stylesheets. This allows for a minimal integrity protection by a proficient user. The integrity values for the currently used files are as follows:

> /resources/js/copy-to-clipboard.js:
> sha256-pdoft+huio0ejiVD+B0WLnFm9Wab+1Yj1nODdPNAZI4=
> 
> /resources/js/decrypt.js:
> sha256-rbZOtsEWrdRylOtuKJGpCMFTvrU4AE2jy2fbbDLteqM=
> 
> /resources/js/encrypt.js:
> sha256-NlYh0r+uul7mzgrlyr+3IR6L3k/qYDR44WH7j9D4CzQ=
> 
> /vendors/asmcrypto/asmcrypto.js:
> sha256-+3Ja+u+3rug2giERjvQSkhc1GZ1jG8ebXZ5TbQe2890=
> 
> /vendors/bootstrap/css/bootstrap.min.css:
> sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=
> 
> /vendors/bootstrap/js/bootstrap.min.js:
> sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=
> 
> /vendors/buffer/index.js:
> sha256-+fItxTnTLDK8HaHyqiP4cD+RxwDK66DqoTE91HqUfnM=
> 
> /vendors/clipboard/clipboard.min.js:
> sha256-YPxFEfHAzLj9n2T+2UXAKGNCRUINk0BexppujiVhRH0=
> 
> /vendors/html5shiv/html5shiv.min.js:
> sha256-3Jy/GbSLrg0o9y5Z5n1uw0qxZECH7C6OQpVBgNFYa0g=
> 
> /vendors/jquery/jquery.min.js:
> sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=
> 
> /vendors/respond/respond.min.js:
> sha256-g6iAfvZp+nDQ2TdTR/VVKJf3bGro4ub5fvWSWVRi2NE=
