### ISSUE TITLE
Thank you for your project - ability to configure settings with environmental variables

### ISSUE THREAD

**Issue by jonico** [syseleven/shared-secrets#15]
@yahesh:  I just wanted to tell you that your project is amazing ✨ 
I am using it to generate one-time credentials as part of the GitHub Pull Request Integration demo with PlanetScale's MySQL SaaS database: https://youtu.be/l3oe7srRUZw?t=610

In order to make your code work in a serverless fashion, I needed to [expose some config.php settings as environmental variables](https://github.com/syseleven/shared-secrets/compare/master...jonico:master#diff-f55db4bc294bbb90108ccfcbdd11881f4707473ad9384b382e2a6b653e118471).

Hence, I am supporting the @macwinnie's changes in https://github.com/syseleven/shared-secrets/pull/14 for faster setup 😊

**Comment by yahesh** [comment]
This feature has been introduced through https://github.com/syseleven/shared-secrets/commit/cc28a74ac246edfea0adf95bc914b96f64f9efb6.
