### ISSUE TITLE
If server has been taken/over or cloned, past secrets can be decrypted if the URL is known

### ISSUE THREAD

**Issue by divVerent** [syseleven/shared-secrets#2]
Essentially, the protection against secrets getting decrypted more than once only works because of a database on the server.

An attacker who can clear this table can easily decrypt a previously decrypted secret a second time.

Proposed solution (sorry, it's complex) - which also fixes #1:

Background operation on server:
- Every 5 minutes (time may vary): server generates a new public/private key pair, and securely deletes all key pairs older than 15 minutes (again, time may vary).
- Also, revocation records may optionally be deleted after the sum of the two time periods above, as the server no longer has a key to decrypt these messages anyway.

Encryption:
- Client requests the newest public key from server.
- Client creates message key.
- Client encrypts message with message key.
- Client encrypts message key with public key received from server.
- Client builds URL out of (server public key ID, encrypted message key, encrypted message).

Decryption:
- Client parses URL.
- Client sends (server public key ID, encrypted message key) to server. (TRICK: these two items could be sent to the server as query string, i.e. after ?, while the encrypted message would go after # as a hash string - that way, no extra request is necessary).
- Server checks if it still has the given public key, and if so, decrypts the encrypted message key.
- Client decrypts the message using the message key it received from the server.

After implementing this, an attacker who took over the server can not decrypt any secret older than 20 minutes before the takeover.

**Comment by weizenspreu** [comment]
This would require the recipient of a secret to act immediately when receiving a secret-sharing link, otherwise the shared secret may get lost. This would introduce a huge burden for the usage of the service.

**Comment by divVerent** [comment]
Right, which is why I'm unsure about the exact times. Maybe something along the lines of "a few days" would still work?

**Comment by weizenspreu** [comment]
Merge with #1, as the same solution applies to both issues.

**Comment by divVerent** [comment]
Good.

BTW, I don't expect all issues I filed to be fixed, as the solution would
end up quite complex - in the end you'll basically end up deciding how much
security can be provided, and seting the expectations by documentation (as
indeed it can't be perfect).

Thank you for the cooperation, and for this indeed interesting project!
