### ISSUE TITLE
MITM attacker on the channel used to transmit the URL may read any secrets

### ISSUE THREAD

**Issue by divVerent** [syseleven/shared-secrets#3]
An active attacker on a chat system used to transmit the secret-sharing URLs may circumvent the only-once restriction by:

- Alice sends secret URL to Mallory (instead of Bob).
- Mallory reads the secret from the service.
- Mallory shares the secret again on the service.
- Mallory sends the new URL to Bob.
- Bob can successfully request the secret, thus believes nobody else has gotten it.

I can imagine no way to fix this in the design, other than requiring a second kind of secret other than the URL itself for decryption. Which kinda defeats the point.

Mitigations include hosting this service only on internal networks, or with additional access control.

**Comment by weizenspreu** [comment]
This may be mitigated by adding signed metadata to the URL (e.g. timestamp, IP address of the sender, some random nonce), that only the server can influence and that the sender can provide to the recipient through a second channel for verification.

**Comment by divVerent** [comment]
Interesting idea, but then you need two channels.

And if you have two channels, you can get _almost_ comparable security by just splitting the URL into two parts.

**Comment by weizenspreu** [comment]
Depending on the chosen second channel, having to copy a second part of the URL may require some effort (think of an SMS). The question is whether implementing a second encryption layer may as well serve this purpose (a user-chosen password sent through a second channel instead of a server-generated token sent through a second channel).

**Comment by divVerent** [comment]
Right, a user-chosen password (that may be used more than once) probably
will make this secure enough for most practical purposes - especially once
the server also can't see the messages any more.

Of course, this project kinda looks like the whole point is not using such
passwords to begin with, and instead relying on the once-only property of
the decryption oracle.

**Comment by weizenspreu** [comment]
Well, it seems as if these are stacked countermeasures against attackers that get more sophisticated:

Current expectation:
The attacker can read the used channel, but is not able to modify it (e.g. a user on a chat channel).

Mentioned expectation:
The attacker can read and write on the used channel (mentioned MITM scenario). Furthermore, the attacker is able to read and write on the server providing the service (mentioned compromised-server scenario).

IMHO the service may provide the second layer of protection when the user wishes to use it, but must not force the user to use the second layer if it is not desired.

**Comment by weizenspreu** [comment]
Merge with #1, as the same solution applies to both issues.
This holds true, unless the attacker is able to MITM both selected channels.

**Comment by divVerent** [comment]
Indeed. The current implementation is safe against attackers who can read
the channel, but not hide/modify messages, and have no control over the
server. And indeed, any extra measures that require user actions, e.g. a
pre-shared key, should be optional. I still think measures against server
compromise (e.g. standalone client, and not sending the message to the
server but just a key guarding the message) would be worth it. Also, I'm OK
with grouping them all under #1.

BTW, as for the current expectation - indeed a funny idea to post such a
link on a public channel. "First person to click gets <something>". I like
this even outside a security related use case.

**Comment by yahesh** [comment]
**Small addition to this issue:** The newest version as of today introduced the possibility to have separate **read-only** and **share-only** instances where a **share-only** instance only allows to create secret sharing links while a **read-only** instance only allows to retrieve secrets.

A user of the service that wants to prevent the above scenario can have an internal **share-only** instance to create secret sharing links (or create the secret sharing links locally). Links passed to recipients should be directed at the **read-only** instance. This way an active attacker (that is not able to access the internal **share-only** instance) could retrieve a secret from the **read-only** instance but not create a new secret sharing link to be passed on to the victim.
