### ISSUE TITLE
ERROR: AN UNKNOWN ERROR OCCURED.

### ISSUE THREAD

**Issue by DerDanilo** [syseleven/shared-secrets#4]
While reading a secret the following error pops up:
"ERROR: AN UNKNOWN ERROR OCCURED."

GPG seems to work fine since it can encrypt secrets. Permission also seem to be fine.

Nginx 1.16
php7.3-fpm
mysql  Ver 15.1 Distrib 10.1.38-MariaDB

**Comment by yahesh** [comment]
Good morning. This general message is used in case any error occurs aside from retrieving a message more than once. You can try to replace the file `actions/read.php` with the one contained in this Gist which provides more granular error messages: https://gist.github.com/yahesh/27ec9aa39c8fc80ddf4443cd29980999

You should undo the change after debugging your issue. :)

**Comment by DerDanilo** [comment]
"ERROR: SECRET COULD NOT BE DECRYPTED."
Well, I don't know why it cannot decrypt. I think that I checked all obvious configuration errors. Any tips on how to debug this further?

**Comment by yahesh** [comment]
Is this a new setup? If yes then there are several possible reasons. Maybe the corresponding private key is not (properly) imported. Or the private key is password-protected and you haven't configured the corresponding passphrase.

**Comment by yahesh** [comment]
I just saw that you're using PHP 7.3. The application has not yet been tested with the newest PHP version. When looking at the changelog for that version there shouldn't be any real problem with that version, especially when you haven't seen any messages in the corresponding error log.

**Comment by ol3k** [comment]
I had the some problem after upgrading Debian to version 9. It seems like the new GPG Version doesn't support passphrases via stdin. 

Solution: enable _loopback pinentry mode_ in gpg
In _~/.gnupg/gpg.conf_ (home of the www-user who has the keyring) add:

```
use-agent 
pinentry-mode loopback
```

**Comment by yahesh** [comment]
@DerDanilo Hi, does this solve your problem?

**Comment by DerDanilo** [comment]
I don't know yet. I will test this soon and give feedback.
The same solution still works for Debian 10 (Buster)?

**Comment by yahesh** [comment]
Tested the configuration of @ol3k on a fresh Debian 10 "Buster" installation and it worked.

**Comment by ol3k** [comment]
I thinks it's just related to the GPG version you are using: https://wiki.archlinux.org/index.php/GnuPG#Unattended_passphrase

Looks like modern/newer packages include the solution mentioned above. (not tested)

The upgrade didn't touch the old gpg.conf and didn't add the needed settings (normal upgrade behavior). 

I guess this problem just affects installations which get an upgrade to GPG >2.1. If you start installing from scratch you never run into this issue.

**Comment by 4001982248998** [comment]
Quick information for Ubuntu Xenial users: You won't get it to work, as GnuPG 2.1.11 throws an error if you try to use loopback mode (https://www.fluidkeys.com/tweak-gpg-2.1.11/). Solution: Update to Bionic.

**Comment by yahesh** [comment]
The encryption of this service has been completely rewritten. We identified a general problem with the integrity assurance of GPG and therefore moved away from GPG entirely. Instead, we implemented an EtM encryption scheme using AES-256-CTR for the encryption and HMAC-SHA-256 for the message authentication. The file `ENCRYPTION.md` describes the implemented encryption schemes in more detail.

Closing this as **wontfix**.

**Comment by yahesh** [comment]
**Small addition to this:** As debugging encryption/decryption problems has been a general problem with the old GPG-based version, the new version introduced the `DEBUG_MODE` configuration value which provides more relevant information about what failed during the encryption or decryption.
