### ISSUE TITLE
ERROR: Insert statement could not be prepared.

### ISSUE THREAD

**Issue by 4001982248998** [syseleven/shared-secrets#9]
Hi,

what could possible wrong when it stubbornly displays ``ERROR: Insert statement could not be prepared``?

Thanks

**Comment by yahesh** [comment]
@4001982248998 Which version are you running on? Have you upgraded from a previous version?

If you have updated from a previous version chances are that you haven't updated the table structure as described in the [release notes of version 0.25b1](https://github.com/syseleven/shared-secrets/releases/tag/0.25b1).

If this is not the case I could have a look at improving the debug output, namely, by adding the `mysqli_error($link)` output to the debug message.

**Comment by 4001982248998** [comment]
Hi, thanks! This was coming from a reinstallation, from where I thought that the table structure already was in place. Guess it wasn't. Uncertainty about the installation's state was the reason for the reinstallation, so I should have known.

After recreating the database, everything worked perfectly.

Cheers!

**Comment by yahesh** [comment]
Nice to hear that the issue has been resolved so quickly. :)

I guess, I'll add the enhanced debug messages in a future release.
